#! /bin/bash
unset	MCEDITOR_INC_editor \
	MCEDITOR_INC_input MCEDITOR_INC_map MCEDITOR_INC_hardness \
	MCEDITOR_INC_print MCEDITOR_INC_block MCEDITOR_INC_enitity \
	MCEDITOR_INC_espmap MCEDITOR_INC_block_proportions MCEDITOR_INC_block_piston \
	MCEDITOR_INC_heap MCEDITOR_INC_print_progress MCEDITOR_INC_container
export dirp=`dirname "$0"`/run
. "$dirp"/editor.sh
editormain "$@"